### ISSUE TITLE
No device listed despite allegedly connected

### ISSUE THREAD

**Issue by Still34** [GameTec-live/ChameleonUltraGUI#369]
**Describe the bug**

![2023-10-30_15-37-34-(chameleonultragui)-](https://github.com/GameTec-live/ChameleonUltraGUI/assets/5843208/6aff6a0b-116a-4182-b508-11c2158089b9)
ChameleonUltraGUI shows an empty list of connected device on the Windows client, despite the ChameleonUltra showing the loading bar animation. COM5 appears to be actively in use when the application is open, suggesting the port is opened and in use by the application. 

The CLI version works fine (compiled locally according to instructions) and can connect to the hardware just fine.
![2023-10-30_15-36-52-(WindowsTerminal)-](https://github.com/GameTec-live/ChameleonUltraGUI/assets/5843208/1693c547-7292-423c-9147-783668702e88)

**To Reproduce**
1. Open the application
2. Connect the device
3. Click refresh
4. No application listed

**Expected behavior**
The device to show up in the application.

**Version info:**
 - OS: Windows 11
 - App build number: 686
 - Connection type: USB
 - Chameleon firmware commit: `gd77e166`

**Also required**:

- [ v ] - I've upgraded app to latest app version

- [ v ] - I've upgraded Chameleon firmware to latest version

- [ v ] - I've searched and verified that there is no already created issues

**Comment by GameTec-live** [comment]
very strange issue... Is nothing else using the COM Port? (eg the CLI)

**Comment by Still34** [comment]
Yes, nothing else should be using the port. Only either the CLI or the GUI is in use at a time.

**Comment by GameTec-live** [comment]
mind enabling production logging in the debug settings and sending a log?

**Comment by Still34** [comment]
```
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to COM1
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:102)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connected to COM1
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:103)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Manufacturer: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:104)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Product: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to COM5
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:102)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connected to COM5
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:103)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Manufacturer: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:104)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Product: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to COM1
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:102)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connected to COM1
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:103)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Manufacturer: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:104)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Product: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to COM5
```

**Comment by GameTec-live** [comment]
your COM ports somehow dont return any manufacturer or Product information? are you running a custom firmware?

**Comment by Still34** [comment]
Nope. The latest available 2.0.0 firmware `- Chameleon Ultra, Version: v2.0 (v2.0.0-110-gd77e166)`

**Comment by Still34** [comment]
For additional context, the Ultra connects just fine and shows up on the GUI on my Linux laptop and iOS device.

**Comment by GameTec-live** [comment]
thats very wierd, because it literlly is the indentical code... (And it works fine for me)

Maybe a driver issue?

**Comment by Foxushka** [comment]
Chameleon is COM1 or COM5 in your case? PM3 client also interferes with our serial library. Try closing all software that can access serial ports

**Comment by Foxushka** [comment]
If you see loading animation on chameleon before selecting chameleon in menu, then there is other software that using it. On main screen we just enumerate them, without connecting

**Comment by Still34** [comment]
>Chameleon is COM1 or COM5 in your case? PM3 client also interferes with our serial library. Try closing all software that can access serial ports

Chameleon should be on COM5 - not entirely sure what's on COM1. 

> If you see loading animation on chameleon before selecting chameleon in menu, then there is other software that using it. On main screen we just enumerate them, without connecting

The animation starts as soon as I open the application, and vice versa when I close it.

**Comment by Still34** [comment]
I just tried it on yet another device - same behavior.

**Comment by Foxushka** [comment]
Can you try on `test-without-exception-handling` branch? Will it throw any errors?

**Comment by Still34** [comment]
I'll test it later tonight. This laptop doesn't have flutter configured yet.

**Comment by Foxushka** [comment]
You can grab compiled version from https://github.com/GameTec-live/ChameleonUltraGUI/actions/runs/6741642455

**Comment by Still34** [comment]
Same issue unfortunately.

**Comment by Foxushka** [comment]
Issue still will be there, something in logs?

**Comment by Still34** [comment]
Roughly the same logs yeah
```
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to COM4
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to COM4
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:102)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connected to COM4
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:103)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Manufacturer: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:104)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Product: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to COM4
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:102)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connected to COM4
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:103)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Manufacturer: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:104)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Product: null
```

**Comment by foXaCe** [comment]
hello i have same problem on arch linux

**Comment by GameTec-live** [comment]
@foXaCe Mind providing some more info? kernel version, app version, debug log output, etc?

**Comment by foXaCe** [comment]
@GameTec-live  yes sorry

Operating System: XeroLinux 
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.3-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 15.5 Gio of RAM
Graphics Processor: AMD Radeon RX 6600 XT



` 
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to /dev/ttyS0
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to /dev/ttyACM0
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to /dev/ttyS0
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to /dev/ttyACM0
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to /dev/ttyS0
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to /dev/ttyACM0
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to /dev/ttyS0
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:88)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:54)
🐛 Connecting to /dev/ttyACM0`



![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/290678/f3403d78-8037-4907-b5f9-d5cefcd99d59)

**Comment by GameTec-live** [comment]
@foXaCe Seems all up to date, only "wierd" thing would be the zen kernel, but that shouldnt change any functionality...
Do you have ModemManager installed? That likes to cause problems. Also; make sure your user has permission to access /dev/ttyS0 (uucp i think is the group on arch based systems)

**Comment by foXaCe** [comment]
how to ?

**Comment by foXaCe** [comment]
sudo gpasswd -a stephane uucp

do not work

**Comment by foXaCe** [comment]
ok work after reboot

thank you

**Comment by GameTec-live** [comment]
> ok work after reboot
> 
> thank you

so its fixed for you? great 👍

**Comment by foXaCe** [comment]
yes thank you

**Comment by 493505110** [comment]
I have same problem when I use android device to connect it with BLE,but MTools BLE is working.

**Comment by tri4ng1e** [comment]
I also has this issue on Windows. On Android, I can connect to the device with both MTools and ChameleonUltraGUI. On the Windows PC, I can connect with the console client, but ChameleonUltraGUI doesn't work.

The logs look the same, indicating that manufacturer and product are null:
```
🐛 Connecting to COM12
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:101)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:53)
🐛 Connected to COM12
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:102)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:53)
🐛 Manufacturer: null
#0   NativeSerial.connectDevice (package:chameleonultragui/connector/serial_native.dart:103)
#1   NativeSerial.availableChameleons (package:chameleonultragui/connector/serial_native.dart:53)
🐛 Product: null
```

Hence, `if (checkPort!.manufacturer == "Proxgrind")` line from `lib/connector/serial_native.dart` discards the device as a non-Chameleon device.

However, USB Device Tree Viewer shows that the device, in fact, has both manufacturer and product fields, which should pass the checks in `serial_native.dart`:
```
Manufacturer String      : Proxgrind
Product String           : ChameleonUltra: hw_v1, fw_v512
```

I don't know much about Flutter and Dart, but if my understanding is correct, ChameleonUltraGUI uses `flutter_libserialport` library, which is a wrapper around Dart's `libserialport` library, which is a wrapper around C library. On the Github page for Dart library, I found a somewhat recent issue related to productID, vendorId, manufacturer and description fields being null on Windows.
https://github.com/jpnurmi/libserialport.dart/issues/85

**Comment by GameTec-live** [comment]
So it looks like we know the issue?
